load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "FREEBSD", "LINUX", "MACOSX", "WINDOWS")

osquery_cxx_library(
    name = "sql",
    srcs = [
        "sql.cpp",
        "sqlite_encoding.cpp",
        "sqlite_filesystem.cpp",
        "sqlite_hashing.cpp",
        "sqlite_math.cpp",
        "sqlite_operations.cpp",
        "sqlite_util.cpp",
        "virtual_sqlite_table.cpp",
        "virtual_table.cpp",
    ],
    header_namespace = "osquery/sql",
    exported_headers = [
        "sqlite_util.h",
        "virtual_table.h",
    ],
    exported_post_platform_linker_flags = [
        (
            FREEBSD,
            [
                "-lfuzzy",
                "-lgflags",
                "-lsqlite3",
            ],
        ),
    ],
    link_whole = True,
    platform_srcs = [
        (
            LINUX,
            [
                "sqlite_string.cpp",
            ],
        ),
        (
            MACOSX,
            [
                "sqlite_string.cpp",
            ],
        ),
        (
            WINDOWS,
            [
                "sqlite_string.cpp",
            ],
        ),
    ],
    tests = [
        ":tests_sql",
        ":tests_sqlite_util",
        ":tests_virtual_table",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/carver:carver"),
        osquery_target("osquery/core:core"),
        osquery_target("osquery/core/plugins:plugins"),
        osquery_target("osquery/hashing:hashing"),
        osquery_target("osquery/utils:utils"),
        osquery_target("osquery/utils/system:errno"),
        osquery_tp_target("boost"),
        osquery_tp_target("gflags"),
        osquery_tp_target("gtest"),
        osquery_tp_target("sqlite"),
        osquery_tp_target("ssdeep-cpp"),
    ],
)

osquery_cxx_test(
    name = "tests_sql",
    srcs = [
        "tests/sql.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/config/plugins:tls_config"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/distributed:distributed"),
        osquery_target("osquery/events:events"),
        osquery_target("osquery/extensions:extensions"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/remote/enroll:tls_enroll"),
        osquery_target("specs:tables"),
        ":sql",
    ],
)

osquery_cxx_test(
    name = "tests_sqlite_util",
    srcs = [
        "tests/sqlite_util.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/config/plugins:tls_config"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/distributed:distributed"),
        osquery_target("osquery/events:events"),
        osquery_target("osquery/extensions:extensions"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/remote/enroll:tls_enroll"),
        osquery_target("specs:tables"),
        ":sql",
    ],
)

osquery_cxx_test(
    name = "tests_virtual_table",
    srcs = [
        "tests/virtual_table.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/config/plugins:tls_config"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/database/plugins:ephemeral"),
        osquery_target("osquery/distributed:distributed"),
        osquery_target("osquery/events:events"),
        osquery_target("osquery/extensions:extensions"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/remote/enroll:tls_enroll"),
        osquery_target("specs:tables"),
        ":sql",
    ],
)
