load("//tools/build_defs/oss/osquery:native.bzl", "osquery_filegroup")
load("//tools/build_defs/oss/osquery:python.bzl", "osquery_python_library")

osquery_python_library(
    name = "utils",
    srcs = [
        "utils.py",
    ],
    base_module = "osquery.tools.tests",
    visibility = ["PUBLIC"],
)

osquery_filegroup(
    name = "conf_files",
    srcs = glob([
        "*.conf",
    ]),
    visibility = ["PUBLIC"],
)

osquery_filegroup(
    name = "plist_files",
    srcs = glob([
        "*.plist",
    ]),
    visibility = ["PUBLIC"],
)
