load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "json",
    srcs = ["json.cpp"],
    header_namespace = "osquery/remote/serializers",
    exported_headers = ["json.h"],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/remote:requests"),
        osquery_target("osquery/utils/json:json"),
        osquery_tp_target("boost"),
    ],
)
