load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "LINUX", "MACOSX", "WINDOWS")

osquery_cxx_library(
    name = "tables",
    platform_deps = [
        (
            LINUX,
            [
                osquery_target("osquery/tables/cloud:cloud"),
                osquery_target("osquery/tables/smart:smart"),
            ],
        ),
        (
            MACOSX,
            [
                osquery_target("osquery/tables/cloud:cloud"),
                osquery_target("osquery/tables/smart:smart"),
            ],
        ),
        (
            WINDOWS,
            [
                osquery_target("osquery/tables/cloud:cloud"),
                osquery_target("osquery/tables/smart:smart"),
            ],
        ),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/tables/applications:applications"),
        osquery_target("osquery/tables/events:events"),
        osquery_target("osquery/tables/forensic:forensic"),
        osquery_target("osquery/tables/lldpd:lldpd"),
        osquery_target("osquery/tables/networking:networking"),
        osquery_target("osquery/tables/sleuthkit:sleuthkit"),
        osquery_target("osquery/tables/system:system"),
        osquery_target("osquery/tables/utility:utility"),
        osquery_target("osquery/tables/yara:yara"),
    ],
)
