load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "FREEBSD", "LINUX", "POSIX", "WINDOWS")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "core",
    srcs = [
        "flags.cpp",
        "init.cpp",
        "query.cpp",
        "system.cpp",
        "tables.cpp",
        "watcher.cpp",
    ],
    header_namespace = "osquery/core",
    exported_headers = [
        "process.h",
        "watcher.h",
    ],
    exported_post_platform_linker_flags = [
        (
            FREEBSD,
            [
                "-lcrypto",
                "-lgflags",
                "-lglog",
            ],
        ),
    ],
    platform_deps = [
        (
            LINUX,
            [
                osquery_tp_target("util-linux"),
            ],
        ),
    ],
    platform_headers = [
        (
            WINDOWS,
            [
                "windows/handle.h",
                "windows/ntapi.h",
                "windows/process_ops.h",
                "windows/wmi.h",
            ],
        ),
    ],
    platform_srcs = [
        (
            POSIX,
            [
                "posix/initializer.cpp",
                "posix/process.cpp",
                "posix/process_ops.cpp",
            ],
        ),
        (
            WINDOWS,
            [
                "windows/handle.cpp",
                "windows/initializer.cpp",
                "windows/process.cpp",
                "windows/process_ops.cpp",
                "windows/wmi.cpp",
            ],
        ),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery:headers"),
        osquery_target("osquery/config:config"),
        osquery_target("osquery/core/plugins:plugins"),
        osquery_target("osquery/core/sql:sql"),
        osquery_target("osquery/filesystem:filesystem"),
        osquery_target("osquery/utils:utils"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/utils/info:info"),
        osquery_target("osquery/utils/system:env"),
        osquery_target("osquery/utils/system:system"),
        osquery_target("osquery/utils/system:time"),
        osquery_tp_target("gflags"),
        osquery_tp_target("glog"),
        osquery_tp_target("gtest"),
        osquery_tp_target("openssl", "crypto"),
    ],
)

osquery_cxx_test(
    name = "tests",
    srcs = [
        "tests/flags_tests.cpp",
        "tests/system_test.cpp",
        "tests/tables_tests.cpp",
    ],
    platform_srcs = [
        (
            POSIX,
            [
                "tests/posix/permissions_tests.cpp",
            ],
        ),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/config/tests:test_utils"),
        osquery_target("osquery/config/plugins:tls_config"),
        osquery_target("osquery/core:core"),
        osquery_target("osquery/core/sql:sql"),
        osquery_target("osquery/utils/info:info"),
        osquery_target("osquery/dispatcher:dispatcher"),
        osquery_target("osquery/distributed:distributed"),
        osquery_target("osquery/events:events"),
        osquery_target("osquery/extensions:extensions"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/remote/enroll:tls_enroll"),
        osquery_target("tests:helper"),
        osquery_target("specs:tables"),
    ],
)
