load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_library(
    name = "logger",
    srcs = ["logger.cpp"],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/core/plugins:plugins"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/filesystem:filesystem"),
        osquery_target("osquery/killswitch:killswitch"),
        osquery_target("osquery/numeric_monitoring:numeric_monitoring"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/utils/info:info"),
        osquery_target("osquery/utils/system:time"),
    ],
)
