load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")

osquery_cxx_test(
    name = "filesystem",
    srcs = [
        "filesystem.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/config/plugins:tls_config"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/numeric_monitoring/plugins:filesystem"),
        osquery_target("osquery/database/plugins:ephemeral"),
        osquery_target("osquery/numeric_monitoring:numeric_monitoring"),
        osquery_target("osquery/extensions:extensions"),
        osquery_target("osquery/remote/enroll:tls_enroll"),
        osquery_target("specs:tables"),
    ],
)
