load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "tls",
    srcs = ["tls.cpp"],
    header_namespace = "osquery/remote/transports",
    exported_headers = ["tls.h"],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery:headers"),
        osquery_target("osquery/core:core"),
        osquery_target("osquery/remote:http_client"),
        osquery_target("osquery/remote:requests"),
        osquery_target("osquery/utils/json:json"),
        osquery_tp_target("boost"),
    ],
)
