load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "FREEBSD")

osquery_cxx_library(
    name = "ephemeral",
    srcs = [
        "ephemeral.cpp",
    ],
    header_namespace = "osquery/database/plugins",
    exported_headers = [
        "ephemeral.h",
    ],
    link_whole = True,
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/utils:utils"),
    ],
)

osquery_cxx_library(
    name = "rocksdb",
    srcs = [
        "rocksdb.cpp",
    ],
    header_namespace = "osquery/database/plugins",
    exported_headers = [
        "rocksdb.h",
    ],
    exported_post_platform_linker_flags = [
        (
            FREEBSD,
            [
                "-lrocksdb-lite",
            ],
        ),
    ],
    link_whole = True,
    tests = [
        osquery_target("osquery/database/plugins/tests:rocksdb"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/utils:utils"),
        osquery_tp_target("gtest"),
        osquery_tp_target("rocksdb"),
    ],
)

osquery_cxx_library(
    name = "sqlite",
    srcs = [
        "sqlite.cpp",
    ],
    header_namespace = "osquery/database/plugins",
    exported_headers = [
        "sqlite.h",
    ],
    exported_post_platform_linker_flags = [
        (
            FREEBSD,
            [
                "-lsqlite3",
            ],
        ),
    ],
    link_whole = True,
    tests = [
        osquery_target("osquery/database/plugins/tests:sqlite"),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/core:core"),
        osquery_target("osquery/database:database"),
        osquery_target("osquery/filesystem:filesystem"),
        osquery_target("osquery/registry:registry"),
        osquery_target("osquery/utils:utils"),
        osquery_tp_target("sqlite"),
    ],
)
