load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "aws",
    srcs = [
        "aws_util.cpp",
    ],
    header_namespace = "osquery/utils/aws",
    exported_headers = [
        "aws_util.h",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/remote:http_client"),
        osquery_target("osquery/remote/transports:tls"),
        osquery_target("osquery/utils/json:json"),
        osquery_target("osquery/utils/status:status"),
        osquery_tp_target("aws-sdk-cpp"),
    ],
)
