load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library", "osquery_cxx_test")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")

osquery_cxx_library(
    name = "json",
    srcs = [
        "json.cpp",
    ],
    header_namespace = "osquery/utils",
    exported_headers = [
        "json.h",
    ],
    exported_preprocessor_flags = [
        "-DRAPIDJSON_NO_SIZETYPEDEFINE",
        "-DRAPIDJSON_HAS_STDSTRING=1",
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/utils:utils"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/utils/status:status"),
        osquery_tp_target("rapidjson"),
    ],
)

osquery_cxx_test(
    name = "tests",
    srcs = [
        "tests/json.cpp",
    ],
    visibility = ["PUBLIC"],
    deps = [
        ":json",
    ],
)
