load("//tools/build_defs/oss/osquery:cxx.bzl", "osquery_cxx_library")
load("//tools/build_defs/oss/osquery:native.bzl", "osquery_target")
load("//tools/build_defs/oss/osquery:third_party.bzl", "osquery_tp_target")
load("//tools/build_defs/oss/osquery:platforms.bzl", "FREEBSD")

osquery_cxx_library(
    name = "devtools",
    srcs = glob(["*.cpp"]),
    header_namespace = "osquery/devtools",
    exported_headers = glob(["*.h"]),
    exported_post_platform_linker_flags = [
        (
            FREEBSD,
            [
                "-llinenoise",
            ],
        ),
    ],
    visibility = ["PUBLIC"],
    deps = [
        osquery_target("osquery/config:config"),
        osquery_target("osquery/core:core"),
        osquery_target("osquery/filesystem:filesystem"),
        osquery_target("osquery/sql:sql"),
        osquery_target("osquery/utils:utils"),
        osquery_target("osquery/utils/conversions:conversions"),
        osquery_target("osquery/utils/system:env"),
        osquery_tp_target("gtest"),
        osquery_tp_target("linenoise"),
    ],
)
